config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/challenges', to: 'home#challenges', as: :challenges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :add_www_subdomain, if: proc { Rails.env.production? }

  private

  def add_www_subdomain
    return if /^www/.match(request.host)

    redirect_to("#{request.protocol}www.hackcolima.com#{request.fullpath}", status: 301)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :resolve_layout

  def index
  end

  def challenges
  end

  private

  def resolve_layout
    case action_name
    when "index"
      "landing"
    else
      "application"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def registration_form_url
    "https://airtable.com/shrdJhPAVSK5ts0fL"
  end
end

app/views/home/challenges.html.slim
section#challenges
  h2.mb-4 Retos
  .row
    .col-12
      p Se trabajarán proyectos de acuerdo a las necesidades detectadas para el Estado de Colima, pero cualquier persona es bienvenida a colaborar bajo los siguientes retos:
      h4 Economía
      ul
        li ¿Cómo proporcionar apoyo económico y alimenticio para las personas que quedan desempleadas ante  la contingencia?
        li ¿Cómo organizarnos como sociedad, mejorar los salarios, digitalizar la mayor cantidad de servicios e incrementar su seguridad?
        li ¿Cómo construir una herramienta de gestión para Gobierno y Sociedad, en la cual se midan las variables:  salud,  economía y educación en forma eficiente y no política?
        li ¿Cómo desarrollamos un sistema emprendedor robusto y eficiente que promueva el empleo y la generación de valor desde la educación básica?
        li ¿Cómo promover y gestar una bolsa económica para ayudar a la población con mayores carencias económicas, sociales y de salud?
      h4 Salud
      ul
        li ¿Cómo mantener la salud física y mental desde casa?
        li ¿Cómo podemos crear un modelo/sistema acertado y confiable para ayudar a los especialistas de la salud a identificar cúmulos de riesgo relacionados a deterioramiento de salud mental o física ?
        li ¿Cómo ayudar técnicamente a los médicos?
      h4 Educación
      ul
        li ¿Cómo fomentar el desarrollo de plataformas educativas?
        li ¿Cómo capacitar a los profesores en herramientas virtuales?
hr.col-3
section#ideas
  h2.mb-4 Ideas
  .row
    .col-12
      p Para que te inspires, aquí tenemos algunas ideas:
      h4 Economía
      ul
        li Robustecer el programa alimentación de gobierno estatal con la donación de productos de la sociedad y con apoyo en la organización y entrega de los mismos.
        li Conformar un comité de la sociedad civil ex profeso que administre donaciones económicas para distribuirlas posteriormente entre la población desempleada por la contingencia o que registre condiciones de pobreza.
        li Para poder mantener un índice de empleo que permita que se genere gasto, tenemos que buscar mantener la mayor cantidad posible de éstos. Negociar con los empleados medios sueldos, medias jornadas. Que todos tengan un ingreso.
        li Propuestas de comercio electrónico para pymes y micropymes.

      h4 Salud
      ul
        li Diseñar rutinas por SMS.
        li Aplicar gamification en una app para retar a amigos o familia y así uno se vea comprometido a hacer más ejercicio.
        li Digitalizar empresas.
        li Conectar hospitales con comunidades “makers” para un mejor suministro de equipo.
        li Conectar app existentes o darles más difusión.
        li Hacer retos de salud y ejercicio intrafamiliares.
        li Ayuda a médicos: ¡¡¡Quédate en casa!!!
        li Campaña de publicidad por todos los medios de hábitos saludables.
        li Salud Física: Distribución de dietas balanceadas, que tomen en cuenta la nutrición y el tipo de alimentos de fácil acceso.

      h4 Educación
      ul
        li Desde las escuelas y universidades impulsar los cursos en línea.
        li Nuevas plataformas digitales de enseñanza.
        li Generar nuevas asignaturas estatales complementarias a la formación Básica en materia de salud y emprendimiento.
  .row.mt-3
    .col-12.text-center.p-3
      a.btn.btn-warning.btn-lg.font-weight-bold href=registration_form_url role="button" ¡QUIERO PARTICIPAR!
      p.mt-3 Tienes hasta el 10 de abril, 5pm CST

hr.col-3
section#info
  .row
    .col-12
      h2.mb-4 Preguntas y más información
      ul.list-unstyled.h4
        li
          a href='https://fb.com/HackColima'
            i.lab.la-facebook
          a href='https://instagram.com/HackColima'
            i.lab.la-instagram
          a href='https://twitter.com/HackColima'
            i.lab.la-twitter
          span.ml-3 HackColima
        li
          i.las.la-envelope
          span.ml-3 daniel@hackcolima.com

app/views/home/index.html.slim
section#brief
  .row.align-items-center
    .d-none.d-md-block.col-md-4
      = image_tag  "team.jpg", class: 'w-100 rounded-circle p-lg-4'
    .col-12.col-md-8
      h2.mb-4 Objetivo
      p Actualmente, en México y el mundo nos encontramos en una situación sin precedentes, causada por la pandemia del Coronavirus (<strong>COVID-19</strong>). La cual dejará estragos, no solo en el área de salud, sino también en la economía de miles sino millones de hogares.
      p Pero, ¡siempre hay esperanza! Como respuesta al COVID-19, realizaremos un evento virtual del tipo Hackathon. Donde buscamos reunir emprendedores, diseñadores, tecnólogos, y miembros de la sociedad; que estén interesados en encontrar y desarrollar soluciones públicas para los retos que se están presentando o avecinan.
      p De acuerdo a las necesidades detectadas para el Estado de Colima, las verticales bajo las cuales se trabajará en este hackatón serán <a href="#{challenges_path}"><strong>Economía, Educación y Salud</strong></a>. Puedes revisar los retos específicos e ideas para inspirarte <a href="#{challenges_path}">aquí</a>.
      p Toma en consideración que, aunque los retos son <em>locales</em>, las soluciones y los participantes pueden venir <strong>desde cualquier parte del mundo</strong>.
hr.col-3
section#hackathon
  .row.mt-3
    .col-12
      h2.mb-4 ¿Qué es un Hackathon y quiénes pueden participar?
      p Es una colaboración colectiva que busca alcanzar una meta en común. Dicho encuentro, generalmente de tecnólogos, tiene el objetivo de desarrollar un software o hardware que cumpla con un fin en específico.
      p No obstante, en este momento ocupamos de todos. Sí, de toda persona que tenga ideas para mitigar el impacto causado por la contingencia del <strong>COVID-19</strong>. Por ejemplo:
  .row.justify-content-center
    .col-6.col-md-4.col-lg-2
      .card.text-center.card--icon
        i.card-img-top.las.la-rocket
        .card-body
          h5 Innovadores
    .col-6.col-md-4.col-lg-2
      .card.text-center.card--icon
        i.card-img-top.las.la-tools
        .card-body
          h5 Creadores
    .col-6.col-md-4.col-lg-2
      .card.text-center.card--icon
        i.card-img-top.las.la-thumbs-up
        .card-body
          h5 Empáticos
    .col-6.col-md-4.col-lg-2
      .card.text-center.card--icon
        i.card-img-top.las.la-user-shield
        .card-body
          h5 Quienes enfrentan el problema directamente
    .col-6.col-md-4.col-lg-2
      .card.text-center.card--icon
        i.card-img-top.las.la-microscope
        .card-body
          h5 Investigadores
  .row
    .col-12.text-center.p-3
      a.btn.btn-warning.btn-lg.font-weight-bold href=registration_form_url role="button" ¡QUIERO PARTICIPAR!
hr.col-3
section#event
  .row
    .col-12
      h2.mb-4 El evento: Hack The Impact (<small>10,11,12 de Abril</small>)
      p Durante 2 días y medio, se pretende desarrollar la propuesta base para aplicaciones móviles o web, así como para diseños industriales, que tengan por objetivo mitigar el impacto de alguno de los efectos que tiene la contingencia provocada por el COVID-19.
      p Así que ¡manos a la obra! Si tienes un proyecto en mente, o quieres colaborar en uno, te invitamos a que te registres y participes.
      p Pasos:
      ol.list
        li
          p.font-weight-bold
            span Regístrate
            i class="las la-handshake h4 ml-1"
        li
          p
            span.font-weight-bold Recibe un correo de confirmación.
            i class="las la-envelope h4 ml-1"
            br
            em Incluye instrucciones y agenda del evento.
        li
          p
            span.font-weight-bold Únete a un equipo.
            i class="las la-user-friends h4 ml-1"
            br
            em El staff del evento te ayudará.
        li
          p.font-weight-bold
            span Comienza a trabajar.
            i class="las la-mug-hot h4 ml-1"
  .row
    .col-12.text-center.p-3
      a.btn.btn-warning.btn-lg.font-weight-bold href=registration_form_url role="button" Regístrate aquí
      p.mt-3 Tienes hasta el 10 de abril, 5pm CST
hr.col-3
section#partners
  .row
    .col-12
      h2.mb-4 Partners
      p Este evento es posible gracias a la colaboración de:
  .row.justify-content-center.text-center.partners-list
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="http://www.col.gob.mx/" style=""
        = image_tag "gobedo.png"
    .col-12.col-md-6.col-lg-4.partners-list-item.hackcolima
      a href="http://www.hackcolima.com/"
        = image_tag "hackcolima.png"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://www.magmalabs.io/"
        = image_tag "magma.png"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://www.codeandomexico.org/"
        = image_tag "codeando.png"
    .col-12.col-md-6.col-lg-4.partners-list-item.tango
      a href="https://tango.io"
        = image_tag "tango.svg"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://a-creativa.negocio.site/"
        = image_tag "acreativa.png"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://toptal.com/"
        = image_tag "toptal.png"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://www.facebook.com/treehousecolima/"
        = image_tag "treehouse.png"
    .col-12.col-md-6.col-lg-4.partners-list-item
      a href="https://apphive.io/es"
        = image_tag "apphive.png"
hr.col-3
section#info
  .row
    .col-12
      h2.mb-4 Preguntas y más información
      ul.list-unstyled.h4
        li
          a href='https://fb.com/HackColima'
            i.lab.la-facebook
          a href='https://instagram.com/HackColima'
            i.lab.la-instagram
          a href='https://twitter.com/HackColima'
            i.lab.la-twitter
          span.ml-3 HackColima
        li
          i.las.la-envelope
          span.ml-3 daniel@hackcolima.com

app/views/layouts/_head.html.slim
title Hack The Impact COVID-19
= csrf_meta_tags
= csp_meta_tag
meta content="width=device-width, user-scalable=no" name="viewport" /
= render 'layouts/social_metatags'
= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_head_message.html.slim
h1 Evento 100% online y gratuito, para desarrollar soluciones que contrarresten los efectos causados por el COVID-19
p.lead
  a.btn.btn-warning.btn-lg.font-weight-bold href=registration_form_url role="button" ¡QUIERO PARTICIPAR!
p
  |Regístrate antes del 10 de abril, 5pm CST

app/views/layouts/_main_menu.html.slim
ul.nav.nav-pills.bg-light.p-2
  li.nav-item
    = link_to "Objetivo", root_path(anchor: "brief"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }
  li.nav-item
    = link_to "Quienes participan", root_path(anchor: "hackathon"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }
  li.nav-item
    = link_to "Retos e Ideas", challenges_path(anchor: "challenges"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }
  li.nav-item
    = link_to "Hack The Impact", root_path(anchor: "event"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }
  li.nav-item
    = link_to "Partners", root_path(anchor: "partners"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }
  li.nav-item
    = link_to "Más información", root_path(anchor: "info"), class: "nav-link text-dark bg-white m-2", data: { turbolinks: "false" }

app/views/layouts/_social_metatags.html.erb
<meta property="og:title" content="Hack The Impact COVID-19">
<meta property="og:description" content="Evento 100% online y gratuito, para desarrollar soluciones que contrarresten los efectos causados por el COVID-19.">
<meta property="og:image" content=<%= image_url("flyer.jpg") -%>>
<meta property="og:url" content="http://www.hackcolima.com/">
<!--  The card type, which will be one of “summary”, “summary_large_image”, “app”, or “player”. -->
<meta name="twitter:card" content="summary_large_image">


<!--  Non-Essential, But Recommended -->

<meta property="og:site_name" content="HackColima">
<meta name="twitter:image:alt" content="Hack The Impact: 10 al 12 de abril 2020">


<!--  Non-Essential, But Required for Analytics -->

<!-- <meta property="fb:app_id" content="your_app_id" />  -->
<meta name="twitter:site" content="@hackcolima">

app/views/layouts/application.html.slim
doctype html
html
  head= render "layouts/head"
  body
    .container
      header.text-white
        .row.align-items-center
          .col-12.col-md-6.main-logo.text-center
            = link_to root_path do
              = image_tag "logo.png"
            h3.mt-n4.mb-4 10, 11 y 12 de Abril 2020, 6:00pm CDT
          .col-12.col-md-6
            .jumbotron.bg-transparent.text-right
              = render "layouts/head_message"

      main
        = render "layouts/main_menu"
        = yield

app/views/layouts/landing.html.slim
doctype html
html
  head= render "layouts/head"
  body
    .container
      header.text-white
        .row.align-items-center
          .offset-md-3.col-md-6.main-logo.text-center
            = link_to root_path do
              = image_tag "logo.png"
            h3 10, 11 y 12 de Abril 2020, 6:00pm CDT
          .col-md-12
            .jumbotron.bg-transparent.text-center
              = render "layouts/head_message"

      main
        = render "layouts/main_menu"
        = yield